### ISSUE TITLE
Fix stop command

### ISSUE THREAD

**Issue by TheCiROMG** [Shadowner/Infrared-Pterodactyl-egg#2]
Add this in the egg section config 

"Stop Command" : ^c

PLUS: Use this container in "bash" format : ghcr.io/parkervcp/installers:debian

And add in the “install script” everything you need

**Comment by Shadowner** [comment]
Will try to fix it in the week 🙂

**Comment by Shadowner** [comment]
Fixed in  #3 #4 #5
